// frontend/src/components/AuthGate.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import { DEFAULT_UNAUTHORIZED_MESSAGE } from "../api";
	import { authContext } from "../lib/context";
	import CenteredNotice from "./CenteredNotice.svelte";

	let { children }: { children: Snippet } = $props();
	const auth = authContext.get();
</script>

{#if auth.status === "authenticated"}
	{@render children()}
{:else}
	<div class="app-shell" data-testid="app-shell">
		<main>
			<CenteredNotice
				variant="error"
				role="alert"
				title="Sign in required"
				body={auth.message ?? DEFAULT_UNAUTHORIZED_MESSAGE}
			>
				<button type="button" onclick={() => auth.reset()}>Try again</button>
			</CenteredNotice>
		</main>
	</div>
{/if}

<style>
	.app-shell {
		min-height: 100dvh;
		max-width: 1234px;
		margin-inline: auto;
	}
</style>

// frontend/src/auth/AuthGate.tsx
import type { ComponentChildren } from "preact";
import { DEFAULT_UNAUTHORIZED_MESSAGE } from "../api";
import { useAuth } from "./AuthContext";

interface AuthGateProps {
	readonly children: ComponentChildren;
}

/**
 * Renders its children while the session is authenticated and a minimal login
 * UI otherwise. There is no backend authentication yet (issue B6), so the
 * "login" is currently a retry prompt; this is the seam where a real sign-in
 * form or OAuth redirect will live once auth is added server-side.
 */
export function AuthGate({ children }: AuthGateProps) {
	const { status, message, reset } = useAuth();

	if (status === "authenticated") {
		return <>{children}</>;
	}

	return (
		<div class="shell">
			<main class="board">
				<div class="empty-state error-state auth-gate" role="alert">
					<p class="empty-title">Sign in required</p>
					<p class="empty-body">{message ?? DEFAULT_UNAUTHORIZED_MESSAGE}</p>
					<button type="button" onClick={reset}>
						Try again
					</button>
				</div>
			</main>
		</div>
	);
}
